services:
  smolform:
    build:
      context: ../..
      dockerfile: dev/remote-pr-opener/Dockerfile
    ports:
      - ${PROPENER_PORT}:3000
    environment:
      PROPENER_REPO_URL: "${PROPENER_REPO_URL}"
      PROPENER_PORT: "${PROPENER_PORT}"
      ROCKET_ADDRESS: "0.0.0.0"
      RUST_LOG: "debug" # TODO: change this
      RUST_BACKTRACE: 1
      PROPENER_FORGEJO_TOKEN: "${PROPENER_FORGEJO_TOKEN}"
      PROPENER_FORGEJO_URL: "${PROPENER_FORGEJO_URL:-https://codeberg.org}"
      PROPENER_REPO_OWNER: "${PROPENER_REPO_OWNER}"
      PROPENER_REPO_NAME: "${PROPENER_REPO_NAME}"
    restart: unless-stopped
