name: Build CI Docker image

on:
  push:
    branches: [main]
    paths: [.github/Dockerfile.ci]
  workflow_dispatch:

jobs:
  build:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install buildah
        run: sudo apt-get install -y buildah

      - name: Login to Codeberg registry
        run: echo "${{ github.token }}" | buildah login --username=${{ github.actor }} --password-stdin codeberg.org

      - name: Build and push with buildah
        run: |
          BUILDAH_ISOLATION=chroot buildah bud \
            --storage-driver vfs \
            --no-cache \
            -t codeberg.org/eldolfin/langton-ci:latest \
            -f .github/Dockerfile.ci \
            .
          buildah --storage-driver vfs push codeberg.org/eldolfin/langton-ci:latest
