name: Build CI Docker image

on:
  push:
    branches: [main]
    paths: [.github/Dockerfile.ci]
  workflow_dispatch:

jobs:
  build:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install podman
        run: apt-get update && apt-get install -y podman

      - name: Login to Codeberg registry
        run: echo "${{ github.token }}" | podman login --username=${{ github.actor }} --password-stdin codeberg.org

      - name: Build and push with podman
        run: |
          podman build \
            --storage-driver vfs \
            --isolation chroot \
            --no-cache \
            -t codeberg.org/eldolfin/langton-ci:latest \
            -f .github/Dockerfile.ci \
            .
          podman push \
            --storage-driver vfs \
            codeberg.org/eldolfin/langton-ci:latest
