name: Run tests & clippy

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          cargo test --verbose
      - name: Run clippy
        run: |
          cargo clippy --verbose -- -Dwarnings
