name: Deploy to pages

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy-path: ${{ steps.prepare.outputs.deploy_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          cd src/langton
          wasm-pack build --target web

      - name: Prepare deploy directory
        id: prepare
        run: |
          DEPLOY_DIR="deploy"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
            DEPLOY_DIR="$DEPLOY_DIR/previews/pr-$PR_NUMBER"
          fi
          mkdir -p "$DEPLOY_DIR"
          cp src/langton/index.html  "$DEPLOY_DIR"
          cp src/langton/favicon.png "$DEPLOY_DIR"
          cp -r src/langton/pkg      "$DEPLOY_DIR"
          echo "deploy_path=$DEPLOY_DIR" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.prepare.outputs.deploy_path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write  # Needed for commenting on PR
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # preview true for PRs to avoid overwriting main, false otherwise
          preview: ${{ github.event_name == 'pull_request' }}

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: peter-evans/comment-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            🚀 Preview deployed at:
            https://eldolfin.github.io/langton.wasm/previews/pr-${{ github.event.pull_request.number }}/
